config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :projects

	root 'home#index'

  get 'projects/' => 'projects#index'
  get 'projects/new' => 'projects#new'
  get 'projects/:id' => 'projects#show'

  get 'bio/' => 'home#bio'
  get 'contact/' => 'home#contact'
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :user
	has_attached_file :image, :styles => {large: "400x500#", thumb: "100x100#"}
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  # I mean I should be the only user right?
  if Rails.env.production?
    devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  else
    devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  end

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show, :bio, :contact]

	def index
		@project = Project.last
	end

	def bio
		render 'bio'
	end

	def contact
		render 'contact'
	end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	before_action :find_project, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		# only show the latest project on the index page
		@projects = Project.all.order("created_at DESC")
	end

	def show
	end

	def new
		@project = current_user.projects.build
	end

	def create
		@project = current_user.projects.build(project_params)

		if @project.save 
			redirect_to @project
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @project.update(project_params)
			redirect_to @project
		else
			render 'edit'
		end
	end

	def destroy
		@project.destroy
		redirect_to root_path 
	end

  private

  def find_project
  	@project = Project.find(params[:id])
  end

  def project_params
  	params.require(:project).permit(:name, :category, :image, :description, :link)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/bio.html.haml
%body
	.bio_wrapper
		.content
			.content_header
				%h1 this works
			%h3 awesome

app/views/home/contact.html.haml
%body
	.contact_wrapper
		.content
			.content_header
				%h1 This worked too
			%h3 As expected

app/views/home/index.html.haml
%header
  .header_wrapper
    .header_title
      %p SAMUEL COLON

    .desc_wrapper 
      %ul
        %li
          .header_image
            %img{:src => '/assets/portrait.png'}
        %li
          .header_bio
            %p  Distillery fashion axe wayfarers Shoreditch heirloom banjo. Try-hard you probably haven't heard of them paleo hashtag scenester. Church-key pork belly kogi banjo. Pinterest mumblecore sustainable beard meggings whatever, distillery bitters salvia VHS chambray YOLO.
  
%body
  .project_wrapper
    .project
      .project_header
        %p#name  Featured Project
        %h1#projectName= @project.name
        / %img{:src => "assets/project_image.jpg"}
        %img= link_to (image_tag @project.image.url(:thumb)), @project
      .project_description
        %p=  @project.description

app/views/layouts/application.html.haml
!!!
%html
	%head
		%title Samuel Colon
		= stylesheet_link_tag    'application', media: 'all', 'dat-		turbolinks-track' => true 
		= javascript_include_tag 'application', 'data-turbolinkstrack'		 => true 
		= csrf_meta_tags 
		%nav.cf
			%ul
				%li
					%a#home{:href => "/"} Home
				%li
					%a#Projects{:href => "/projects"} Projects
				%li
					%a#Bio{:href => "/bio"} Bio
				%li
					%a#Contact{:href => "/contact"} Contact

	%body
		.yield_wrapper		
			= yield

app/views/projects/_form.html.haml
= simple_form_for @project do |f|
	= f.input :name
	= f.input :description
	= f.input :category
	= f.input :image
	= f.button :submit

app/views/projects/edit.html.haml
%h3 edit your post

= render 'form'

app/views/projects/index.html.haml
%projects_wrapper
	%ul
		- @projects.each do |p|
			%li
				.project_tile
					.project_header
						%p#name= p.name
						= link_to (image_tag p.image.url(:thumb)), p
						%p#category= p.category
						%p#description= p.description		

app/views/projects/new.html.haml
%h1 new post form

= render 'form'

app/views/projects/show.html.haml
%body#show
	.project_wrapper#show
		.project
			.project_header	
				%h1= @project.name
				%h3= @project.category
			= image_tag @project.image.url(:large)
			%p= @project.description

- if user_signed_in?
	= link_to "Edit", edit_project_path(@project)
	= link_to "Destroy",  project_path(@project), method: :delete, data: {confim: "Are you sure?"}